# Generated by Django 5.1.3 on 2024-11-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
