# Generated by Django 5.1.3 on 2024-11-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_blog_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="reading_time",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
