# Generated by Django 5.1.3 on 2024-11-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_blog_reading_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
